<?php
  $json = file_get_contents("https://covid19.ddc.moph.go.th/api/Cases/today-cases-by-provinces");
  $data = json_decode($json);

  echo "<table border='1'>";
  echo"<caption>";
  echo "<h3>";
  echo "<p>";
  echo "รายงานสถานการโควิด-19 แยกจังหวัด";
  echo "</p>";
  echo "</h3>";
  echo"</caption>";
  echo "<tr align = 'center'>";
  echo "<td bgcolor='#FC3131'>"; 
  echo "ลำดับ";
  echo "</td>"; 
  echo "<td bgcolor='#FF552F'>"; 
  echo "จังหวัด";
  echo "</td>";
  echo "<td bgcolor='#FF7114'>"; 
  echo "ผู้ป่วยใหม่";
  echo "</td>"; 
  echo "<td bgcolor='#FFE71D'>"; 
  echo "ผู้ป่วยรวม";
  echo "</td>"; 
  echo "<td bgcolor='#49FF24'>"; 
  echo "ผู้ป่วยใหม่ในประเทศ";
  echo "</td>"; 
  echo "<td bgcolor='#19FFF1'>"; 
  echo "ผู้ป่วยรวมในประเทศ";
  echo "</td>"; 
  echo "<td bgcolor='#6370FE'>"; 
  echo "ผู้เสียชีวิตใหม่";
  echo "</td>"; 
  echo "<td bgcolor='#A059FF'>"; 
  echo "ผู้เสียชีวิตรวม";
  echo "</td>";
  echo "<td bgcolor='#F176FF'>"; 
  echo "วันที่อัพเดท";
  echo "</td>";  
  echo "</tr>";

  foreach($data as $key=>$val){
    echo "<tr align = 'center'>";
    echo "<tr align = 'center'>";
    echo "<td bgcolor='#FF7575'>"; 
    echo $key+1;
    echo "</td>"; 
    echo "<td bgcolor='#FF8165'>"; 
    echo $val->province;
    echo "</td>";
    echo "<td bgcolor='#FF944E'>"; 
    echo $val->new_case;
    echo "</td>";
    echo "<td bgcolor='#F8F989'>"; 
    echo $val->total_case;
    echo "</td>";
    echo "<td bgcolor='#99FD90'>"; 
    echo $val->new_case_excludeabroad;
    echo "</td>";
    echo "<td bgcolor='#99FDFF'>"; 
    echo $val->total_case_excludeabroad;
    echo "</td>";
    echo "<td bgcolor='#7984FE'>"; 
    echo $val->new_death;
    echo "</td>";
    echo "<td bgcolor='#B883FF'>"; 
    echo $val->total_death;
    echo "</td>"; 
    echo "<td bgcolor='#E39EFE'>"; 
    echo $val->update_date;
    echo "</td>";
    echo "</tr>";

  }
  echo "</table>";
